// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rockaway.WebApp.Data;

#nullable disable

namespace Rockaway.WebApp.Migrations
{
    [DbContext(typeof(RockawayDbContext))]
    [Migration("20240123170838_CreateTicketOrders")]
    partial class CreateTicketOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "rockaway-sample-admin-user",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b9a44f7-cc16-4c5f-86ec-ea392abc27ab",
                            Email = "admin@rockaway.dev",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ROCKAWAY.DEV",
                            NormalizedUserName = "ADMIN@ROCKAWAY.DEV",
                            PasswordHash = "AQAAAAIAAYagAAAAEImvuoFcqmHCvxKJtFmmPR73NapKhSf8PjDWbz3lC2lp7WKm12nwCSsDupwh9zpFsg==",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f77dc522-8f80-4fd2-8253-705df167330a",
                            TwoFactorEnabled = false,
                            UserName = "admin@rockaway.dev"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            Description = "Alter Column are South Africa's hottest math rock export. Founded in Cape Town in 2021, their debut album \"Drop Table Mountain\" was nominated for four Grammy awards.",
                            Name = "Alter Column",
                            Slug = "alter-column"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            Description = "Speed metal pioneers from San Francisco, <Body>Bag helped define the “web rock” sound in the early 2020s.",
                            Name = "<Body>Bag",
                            Slug = "body-bag"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            Description = "Hailing from a distant future, Coda is a time-traveling rock band known for their mind-bending melodies that transport audiences through different eras, merging past and future into a harmonious blend of sound.",
                            Name = "Coda",
                            Slug = "coda"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            Description = "Rising from the ashes of adversity, Dev Leppard is a fiercely talented rock band that overcame obstacles with sheer determination, captivating fans worldwide with their electrifying performances and showcasing a bond that empowers their music.",
                            Name = "Dev Leppard",
                            Slug = "dev-leppard"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5"),
                            Description = "Merging the realms of art and emotion, Электроника is an introspective rock group, infusing their hauntingly beautiful lyrics with mesmerizing melodies that delve into the depths of human existence, leaving listeners immersed in profound reflections.",
                            Name = "Электроника",
                            Slug = "elektronika"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6"),
                            Description = "With an otherworldly allure, For Ear Transform is an ethereal rock ensemble, their music transcends reality, leading listeners on a dreamlike journey where celestial harmonies and ethereal instrumentation create a captivating and transformative experience.",
                            Name = "For Ear Transform",
                            Slug = "for-ear-transform"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa7"),
                            Description = "Rebel rockers with a cause, Garbage Collectors are raw, raucous and unapologetic, fearlessly tackling social issues and societal norms in their music, energizing crowds with their powerful anthems and unyielding spirit.",
                            Name = "Garbage Collectors",
                            Slug = "garbage-collectors"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa8"),
                            Description = "Virtuosos of rhythm and harmony, Haskell’s Angels radiate a divine aura, blending complex melodies and celestial harmonies that resonate deep within the soul.",
                            Name = "Haskell’s Angels",
                            Slug = "haskells-angels"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa9"),
                            Description = "A force to be reckoned with, Iron Median are known for their thunderous beats and adrenaline-pumping anthems, electrifying audiences with their commanding stage presence and unstoppable energy.",
                            Name = "Iron Median",
                            Slug = "iron-median"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10"),
                            Description = "Enigmatic and mysterious, Java’s Crypt are shrouded in secrecy, their enigmatic melodies and cryptic lyrics take listeners on a thrilling journey through the unknown realms of music.",
                            Name = "Java’s Crypt",
                            Slug = "javas-crypt"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11"),
                            Description = "An electrifying whirlwind, Killer Bite unleash a torrent of energy through their performances, captivating audiences with their explosive riffs and heart-pounding rhythms.",
                            Name = "Killer Bite",
                            Slug = "killer-bite"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa12"),
                            Description = "Pioneers of progressive rock, Lambda of God is an innovative band that pushes the boundaries of musical expression, combining intricate compositions and thought-provoking lyrics that resonate deeply with their dedicated fanbase.",
                            Name = "Lambda of God",
                            Slug = "lambda-of-god"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa14"),
                            Description = "A charismatic ensemble, Mott the Tuple blends vintage charm with a modern edge, creating a unique sound that captivates audiences and takes them on a nostalgic journey through time.",
                            Name = "Mott the Tuple",
                            Slug = "mott-the-tuple"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa13"),
                            Description = "Quirky and witty, the Null Terminated String Band is a rock group that weaves clever humor and geeky references into their catchy tunes, bringing a smile to the faces of both tech enthusiasts and music lovers alike.",
                            Name = "Null Terminated String Band",
                            Slug = "null-terminated-string-band"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa15"),
                            Description = "Overflowing with passion and intensity, Överflow is a rock band that immerses listeners in a tsunami of sound, exploring emotions through powerful melodies and soul-stirring performances.",
                            Name = "Överflow",
                            Slug = "overflow"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa16"),
                            Description = "Philosophers of rock, Pascal’s Wager delves into existential themes with their intellectually charged songs, prompting listeners to ponder the profound questions of life and purpose.",
                            Name = "Pascal’s Wager",
                            Slug = "pascals-wager"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa17"),
                            Description = "Futuristic and avant-garde, Qüantum Gäte defy conventions, using experimental sounds and innovative compositions to transport listeners to other dimensions of music.",
                            Name = "Qüantum Gäte",
                            Slug = "quantum-gate"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa18"),
                            Description = "High-energy and rebellious, Run CMD is a rock band that merges technology themes with headbanging-worthy tunes, igniting the stage with their electrifying presence and infectious enthusiasm.",
                            Name = "Run CMD",
                            Slug = "run-cmd"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa19"),
                            Description = "Mischievous and bold, <Script>Kiddies subvert expectations with clever musical pranks, weaving clever wordplay and tongue-in-cheek humor into their audacious performances.",
                            Name = "<Script>Kiddies",
                            Slug = "script-kiddies"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa20"),
                            Description = "Masters of atmosphere, Terrorform’s dark and atmospheric rock ensembles conjure hauntingly beautiful soundscapes that captivate the senses and evoke a deep emotional response.",
                            Name = "Terrorform",
                            Slug = "terrorform"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa21"),
                            Description = "ᵾnɨȼøđɇɍ harmonize complex equations and melodies, weaving a symphony of logic and emotion in their unique and captivating music.",
                            Name = "ᵾnɨȼøđɇɍ",
                            Slug = "unicoder"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa22"),
                            Description = "Bridging reality and virtuality, Virtual Machine is a surreal rock group that blurs the lines between the tangible and the digital, creating mind-bending performances that leave audiences questioning the nature of existence.",
                            Name = "Virtual Machine",
                            Slug = "virtual-machine"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa23"),
                            Description = "Technologically savvy and creatively ambitious, Webmaster of Puppets is a web-inspired rock band, crafting narratives of digital dominance and manipulation with their inventive music.",
                            Name = "Webmaster of Puppets",
                            Slug = "webmaster-of-puppets"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa24"),
                            Description = "Mesmerizing and genre-defying, XSLTE is an enchanting rock ensemble that fuses electronic and rock elements, creating a spellbinding sound that enthralls listeners and transports them to MakeArtist sonic landscapes.",
                            Name = "XSLTE",
                            Slug = "xslte"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa25"),
                            Description = "Youthful and exuberant, YAMB spreads positivity and infectious energy through their music, connecting with fans through their youthful spirit and heartwarming performances.",
                            Name = "YAMB",
                            Slug = "yamb"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa26"),
                            Description = "Innovative and exploratory, Zero Based Index starts from scratch, building powerful narratives through their dynamic sound, leaving audiences inspired and moved by their expressive and daring music.",
                            Name = "Zero Based Index",
                            Slug = "zero-based-index"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa27"),
                            Description = "Inspired by their Australian namesakes, Ærbårn are Scandinavia's #1 party rock band. Thundering drums, huge guitar riffs and enough energy to light up the Arctic Circle, their shows have had amazing reviews all over the world",
                            Name = "Ærbårn",
                            Slug = "aerbaarn"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa28"),
                            Description = "dot-dot-dot to their friends (and fans), ... are a Canadian drone jazz combo formed in Vancouver in 1998, known for their thunderous horn section and innovative visuals.",
                            Name = "...",
                            Slug = "dot-dot-dot"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa29"),
                            Description = "Known as the \"Silver Mountain Strings\" if you're into the whole brevity thing, Kentucky's answer to the Leningrad Cowboys has gone from strength to strength, from the Superbowl half time show to their sold-out Vegas residency in 2023.",
                            Name = "The Silver Mountain String Band featuring Timber J. MacCorkindale and the Hill Valley Hornswogglers",
                            Slug = "silver-mountain-string-band"
                        });
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.Show", b =>
                {
                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("HeadlineArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VenueId", "Date");

                    b.HasIndex("HeadlineArtistId");

                    b.ToTable("Show");

                    b.HasData(
                        new
                        {
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7"),
                            Date = new DateOnly(2024, 5, 17),
                            HeadlineArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        },
                        new
                        {
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            Date = new DateOnly(2024, 5, 18),
                            HeadlineArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        },
                        new
                        {
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Date = new DateOnly(2024, 5, 19),
                            HeadlineArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        },
                        new
                        {
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9"),
                            Date = new DateOnly(2024, 5, 20),
                            HeadlineArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        },
                        new
                        {
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            Date = new DateOnly(2024, 5, 22),
                            HeadlineArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        },
                        new
                        {
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8"),
                            Date = new DateOnly(2024, 5, 23),
                            HeadlineArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        },
                        new
                        {
                            VenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            Date = new DateOnly(2024, 5, 25),
                            HeadlineArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3")
                        });
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.SupportSlot", b =>
                {
                    b.Property<Guid>("ShowVenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ShowDate")
                        .HasColumnType("date");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ShowVenueId", "ShowDate", "SlotNumber");

                    b.HasIndex("ArtistId");

                    b.ToTable("SupportSlot");

                    b.HasData(
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7"),
                            ShowDate = new DateOnly(2024, 5, 17),
                            SlotNumber = 1,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7"),
                            ShowDate = new DateOnly(2024, 5, 17),
                            SlotNumber = 2,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa15")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            ShowDate = new DateOnly(2024, 5, 18),
                            SlotNumber = 1,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            ShowDate = new DateOnly(2024, 5, 18),
                            SlotNumber = 2,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa15")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            ShowDate = new DateOnly(2024, 5, 19),
                            SlotNumber = 1,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa11")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            ShowDate = new DateOnly(2024, 5, 19),
                            SlotNumber = 2,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa15")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            ShowDate = new DateOnly(2024, 5, 19),
                            SlotNumber = 3,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9"),
                            ShowDate = new DateOnly(2024, 5, 20),
                            SlotNumber = 1,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            ShowDate = new DateOnly(2024, 5, 22),
                            SlotNumber = 1,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8"),
                            ShowDate = new DateOnly(2024, 5, 23),
                            SlotNumber = 1,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            ShowDate = new DateOnly(2024, 5, 25),
                            SlotNumber = 1,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10")
                        },
                        new
                        {
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            ShowDate = new DateOnly(2024, 5, 25),
                            SlotNumber = 2,
                            ArtistId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa29")
                        });
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.TicketOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("ShowDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ShowVenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShowVenueId", "ShowDate");

                    b.ToTable("TicketOrder");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.TicketOrderItem", b =>
                {
                    b.Property<Guid>("TicketOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TicketTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("TicketOrderId", "TicketTypeId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("TicketOrderItem");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.TicketType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Limit")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<DateOnly>("ShowDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ShowVenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShowVenueId", "ShowDate");

                    b.ToTable("TicketType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf355665-288e-4c4a-8075-bfeea2f10c73"),
                            Name = "Upstairs unallocated seating",
                            Price = 25m,
                            ShowDate = new DateOnly(2024, 5, 17),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7")
                        },
                        new
                        {
                            Id = new Guid("4ca6cab5-0e04-4abb-a310-83b9b9e34a52"),
                            Name = "Downstairs standing",
                            Price = 25m,
                            ShowDate = new DateOnly(2024, 5, 17),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7")
                        },
                        new
                        {
                            Id = new Guid("f1a3e169-995d-41eb-97c8-0a00e1838248"),
                            Name = "Cabaret table (4 people)",
                            Price = 120m,
                            ShowDate = new DateOnly(2024, 5, 17),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7")
                        },
                        new
                        {
                            Id = new Guid("e01be398-c103-4d18-b085-e0dd38df0e38"),
                            Name = "General Admission",
                            Price = 35m,
                            ShowDate = new DateOnly(2024, 5, 18),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3")
                        },
                        new
                        {
                            Id = new Guid("89a3141b-3191-4cd6-b4a4-dc5fed127259"),
                            Name = "VIP Meet & Greet",
                            Price = 75m,
                            ShowDate = new DateOnly(2024, 5, 18),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3")
                        },
                        new
                        {
                            Id = new Guid("55ff6e9d-e091-461a-ab30-b9359900a4c1"),
                            Name = "General Admission",
                            Price = 35m,
                            ShowDate = new DateOnly(2024, 5, 19),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2")
                        },
                        new
                        {
                            Id = new Guid("2fc6d145-6075-4c10-8326-ca7adb5b5727"),
                            Name = "VIP Meet & Greet",
                            Price = 75m,
                            ShowDate = new DateOnly(2024, 5, 19),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2")
                        },
                        new
                        {
                            Id = new Guid("8e92740d-c283-4de6-a2ec-c8a850212d45"),
                            Name = "General Admission",
                            Price = 25m,
                            ShowDate = new DateOnly(2024, 5, 20),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9")
                        },
                        new
                        {
                            Id = new Guid("f25b372e-1506-4737-a72d-44a0eef445fa"),
                            Name = "VIP Meet & Greet",
                            Price = 55m,
                            ShowDate = new DateOnly(2024, 5, 20),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9")
                        },
                        new
                        {
                            Id = new Guid("fd6b57d6-8404-4034-96ba-1af87baca65b"),
                            Name = "General Admission",
                            Price = 350m,
                            ShowDate = new DateOnly(2024, 5, 22),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5")
                        },
                        new
                        {
                            Id = new Guid("3352b1ab-605f-49bc-b938-141d68eb7bc7"),
                            Name = "VIP Meet & Greet",
                            Price = 750m,
                            ShowDate = new DateOnly(2024, 5, 22),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5")
                        },
                        new
                        {
                            Id = new Guid("7a97fa4c-ae29-4180-abac-6777f61657c4"),
                            Name = "General Admission",
                            Price = 300m,
                            ShowDate = new DateOnly(2024, 5, 23),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8")
                        },
                        new
                        {
                            Id = new Guid("ade83857-69ff-4ee5-a0a6-18a7f23ddfd3"),
                            Name = "VIP Meet & Greet",
                            Price = 720m,
                            ShowDate = new DateOnly(2024, 5, 23),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8")
                        },
                        new
                        {
                            Id = new Guid("c435a52f-e4df-4921-abf7-55b9e5688e77"),
                            Name = "General Admission",
                            Price = 25m,
                            ShowDate = new DateOnly(2024, 5, 25),
                            ShowVenueId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4")
                        });
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CultureName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Venue");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Address = "Town Hall Parade",
                            City = "London",
                            CultureName = "en-GB",
                            Name = "Electric Brixton",
                            PostalCode = "SW2 1RJ",
                            Slug = "electric-brixton",
                            Telephone = "020 7274 2290",
                            WebsiteUrl = "https://www.electricbrixton.uk.com/"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Address = "50 Boulevard Voltaire",
                            City = "Paris",
                            CultureName = "fr-FR",
                            Name = "Bataclan",
                            PostalCode = "75011",
                            Slug = "bataclan-paris",
                            Telephone = "+33 1 43 14 00 30",
                            WebsiteUrl = "https://www.bataclan.fr/"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            Address = "Columbiadamm 9 - 11",
                            City = "Berlin",
                            CultureName = "de-DE",
                            Name = "Columbia Theatre",
                            PostalCode = "10965",
                            Slug = "columbia-berlin",
                            Telephone = "+49 30 69817584",
                            WebsiteUrl = "https://columbia-theater.de/"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            Address = "Liosion 205",
                            City = "Athens",
                            CultureName = "el-GR",
                            Name = "Gagarin 205",
                            PostalCode = "104 45",
                            Slug = "gagarin-athens",
                            Telephone = "+45 35 35 50 69",
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            Address = "Torggata 16",
                            City = "Oslo",
                            CultureName = "nn-NO",
                            Name = "John Dee Live Club & Pub",
                            PostalCode = "0181",
                            Slug = "john-dee-oslo",
                            Telephone = "+47 22 20 32 32",
                            WebsiteUrl = "https://www.rockefeller.no/"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6"),
                            Address = "Stengade 18",
                            City = "Copenhagen",
                            CultureName = "da-DK",
                            Name = "Stengade",
                            PostalCode = "2200",
                            Slug = "stengade-copenhagen",
                            Telephone = "+45 35355069",
                            WebsiteUrl = "https://www.stengade.dk"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb7"),
                            Address = "R da Madeira 186",
                            City = "Porto",
                            CultureName = "pt-PT",
                            Name = "Barracuda",
                            PostalCode = "4000-433",
                            Slug = "barracuda-porto"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb8"),
                            Address = "Sveavägen 90",
                            City = "Stockholm",
                            CultureName = "sv-SE",
                            Name = "Pub Anchor",
                            PostalCode = "113 59",
                            Slug = "pub-anchor-stockholm",
                            Telephone = "+46 8 15 20 00",
                            WebsiteUrl = "https://www.instagram.com/pubanchor/?hl=en"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb9"),
                            Address = "323 New Cross Road",
                            City = "London",
                            CultureName = "en-GB",
                            Name = "New Cross Inn",
                            PostalCode = "SE14 6AS",
                            Slug = "new-cross-inn-london",
                            Telephone = "+44 20 8469 4382",
                            WebsiteUrl = "https://www.newcrossinn.com/"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.Show", b =>
                {
                    b.HasOne("Rockaway.WebApp.Data.Entities.Artist", "HeadlineArtist")
                        .WithMany("HeadlineShows")
                        .HasForeignKey("HeadlineArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rockaway.WebApp.Data.Entities.Venue", "Venue")
                        .WithMany("Shows")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeadlineArtist");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.SupportSlot", b =>
                {
                    b.HasOne("Rockaway.WebApp.Data.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rockaway.WebApp.Data.Entities.Show", "Show")
                        .WithMany("SupportSlots")
                        .HasForeignKey("ShowVenueId", "ShowDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.TicketOrder", b =>
                {
                    b.HasOne("Rockaway.WebApp.Data.Entities.Show", null)
                        .WithMany("TicketOrders")
                        .HasForeignKey("ShowVenueId", "ShowDate");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.TicketOrderItem", b =>
                {
                    b.HasOne("Rockaway.WebApp.Data.Entities.TicketOrder", "TicketOrder")
                        .WithMany("Contents")
                        .HasForeignKey("TicketOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rockaway.WebApp.Data.Entities.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketOrder");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.TicketType", b =>
                {
                    b.HasOne("Rockaway.WebApp.Data.Entities.Show", "Show")
                        .WithMany("TicketTypes")
                        .HasForeignKey("ShowVenueId", "ShowDate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.Artist", b =>
                {
                    b.Navigation("HeadlineShows");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.Show", b =>
                {
                    b.Navigation("SupportSlots");

                    b.Navigation("TicketOrders");

                    b.Navigation("TicketTypes");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.TicketOrder", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Rockaway.WebApp.Data.Entities.Venue", b =>
                {
                    b.Navigation("Shows");
                });
#pragma warning restore 612, 618
        }
    }
}
